# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test8AsignarProductoTienda():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_8AsignarProductoTienda(self):
    self.driver.get("http://localhost:64927/")
    self.driver.set_window_size(1920, 1032)
    self.driver.find_element(By.NAME, "clave").click()
    self.driver.find_element(By.NAME, "clave").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Compras").click()
    self.driver.find_element(By.LINK_TEXT, "Asignar producto a Tienda").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-bars > path").click()
    self.driver.find_element(By.ID, "btnBuscarTienda").click()
    element = self.driver.find_element(By.ID, "btnBuscarTienda")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#tbTienda .svg-inline--fa").click()
    self.driver.find_element(By.ID, "btnBuscarProducto").click()
    self.driver.find_element(By.CSS_SELECTOR, ".odd:nth-child(5) .svg-inline--fa").click()
    self.driver.find_element(By.ID, "btnAsignar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-trash").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, "strong").click()
  
