# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test6RegistrarNuevosClientes():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_6RegistrarNuevosClientes(self):
    self.driver.get("http://localhost:64927/")
    self.driver.set_window_size(1920, 1032)
    self.driver.find_element(By.NAME, "clave").click()
    self.driver.find_element(By.NAME, "clave").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Clientes").click()
    self.driver.find_element(By.NAME, "Clientes").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "txtNumeroDocumento").click()
    self.driver.find_element(By.ID, "txtNumeroDocumento").send_keys("12345678")
    self.driver.find_element(By.ID, "txtNombres").click()
    self.driver.find_element(By.ID, "txtNombres").send_keys("Marcos Montero")
    self.driver.find_element(By.ID, "txtDireccion").click()
    self.driver.find_element(By.ID, "txtDireccion").send_keys("av. Test 777")
    self.driver.find_element(By.ID, "txtTelefono").click()
    self.driver.find_element(By.ID, "txtTelefono").send_keys("12345678")
    self.driver.find_element(By.ID, "btnGuardarCambios").click()
    self.driver.find_element(By.LINK_TEXT, "2").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(8) > td:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(8) .btn-danger path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt > path").click()
  
